<a href="https://colab.research.google.com/github/Bipingundala/Predictive-analysis/blob/customer_churn/Customerchurnprediction_ensemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
df=pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [5]:
print(df)

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95        1889.5
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 21 columns]

In [8]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [10]:
print(len(df.columns))

21

In [13]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [15]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [19]:
df['Churn']

0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: object

In [20]:
# Split features and target
X = df.drop('Churn', axis=1)  # Drop the target column to get features
y = df['Churn']  # Select the target column

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [25]:
# Print the shapes of the resulting splits to confirm the operation
print(f"Training features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")
print(f"Training labels shape: {y_train.shape}")
print(f"Testing labels shape: {y_test.shape}")

Training features shape: (4930, 20)
Testing features shape: (2113, 20)
Training labels shape: (4930,)
Testing labels shape: (2113,)

In [29]:
# Identify categorical columns
categorical_columns = df.select_dtypes(include=['object', 'category']).columns

# Print the list of categorical columns
print("Categorical Columns:\n", categorical_columns)

Categorical Columns:
 Index([], dtype='object')

In [30]:
# Get information about the DataFrame including data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   int64
 1   gender            7043 non-null   int64
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   int64
 4   Dependents        7043 non-null   int64
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   int64
 7   MultipleLines     7043 non-null   int64
 8   InternetService   7043 non-null   int64
 9   OnlineSecurity    7043 non-null   int64
 10  OnlineBackup      7043 non-null   int64
 11  DeviceProtection  7043 non-null   int64
 12  TechSupport       7043 non-null   int64
 13  StreamingTV       7043 non-null   int64
 14  StreamingMovies   7043 non-null   int64
 15  Contract          7043 non-null   int64
 16  PaperlessBilling  7043 non-null   int64
 17  PaymentMethod     7043 non-null   int64
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   int64
 20  Churn             7043 non-null   int64
dtypes: float64(1), int64(20)
memory usage: 1.1 MB

In [27]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

# Step 1: Load the dataset
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

# Step 2: Preprocessing
# Check for missing values
print("Missing values in each column:\n", df.isnull().sum())



# Convert categorical columns to numeric using Label Encoding
# List of categorical columns that need encoding
categorical_columns = df.select_dtypes(include=['object']).columns

# Initialize LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to each categorical column
for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

# Step 3: Split features and target
X = df.drop('Churn', axis=1)  # Features
y = df['Churn']  # Target variable

# Step 4: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 5: Initialize and train the Gradient Boosting model
# Using subsampling for Stochastic Gradient Boosting
model = GradientBoostingClassifier(subsample=0.8, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Step 6: Make predictions on the test set
y_pred = model.predict(X_test)

# Step 7: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

# Print classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Missing values in each column:
 customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64
Model Accuracy: 80.88%

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.92      0.87      1539
           1       0.70      0.52      0.60       574

    accuracy                           0.81      2113
   macro avg       0.77      0.72      0.74      2113
weighted avg       0.80      0.81      0.80      2113

In [28]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

# Step 1: Load the dataset
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')



# Convert categorical columns to numeric using Label Encoding
categorical_columns = df.select_dtypes(include=['object']).columns

# Initialize LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to each categorical column
for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

# Step 3: Split features and target
X = df.drop('Churn', axis=1)  # Features
y = df['Churn']  # Target variable

# Step 4: Split the data into training and testing sets (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 5: Initialize and train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

# Step 6: Make predictions on the test set
y_pred = rf_model.predict(X_test)

# Step 7: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

# Print classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Model Accuracy: 79.89%

Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.91      0.87      1539
           1       0.68      0.50      0.57       574

    accuracy                           0.80      2113
   macro avg       0.75      0.71      0.72      2113
weighted avg       0.79      0.80      0.79      2113

In [34]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.impute import SimpleImputer

# Step 1: Load the dataset
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

# Step 2: Preprocessing

# Convert categorical columns to numeric using Label Encoding
categorical_columns = df.select_dtypes(include=['object', 'category']).columns

# Initialize LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to each categorical column (excluding the target 'Churn')
for col in categorical_columns:
    if col != 'Churn':  # Exclude target column
        df[col] = le.fit_transform(df[col])

# Step 3: Split features and target
X = df.drop('Churn', axis=1)  # Features
y = df['Churn']  # Target variable

# Step 4: Split the data into training and testing sets (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 5: Initialize and train the KNN model (with K=5)
knn_model = KNeighborsClassifier(n_neighbors=5)

# Train the model
knn_model.fit(X_train, y_train)

# Step 6: Make predictions on the test set
y_pred = knn_model.predict(X_test)

# Step 7: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

# Print classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Confusion matrix (for more detailed evaluation)
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Model Accuracy: 68.43%

Classification Report:
               precision    recall  f1-score   support

          No       0.74      0.89      0.80      1539
         Yes       0.32      0.14      0.20       574

    accuracy                           0.68      2113
   macro avg       0.53      0.52      0.50      2113
weighted avg       0.62      0.68      0.64      2113


Confusion Matrix:
 [[1363  176]
 [ 491   83]]

In [33]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
from sklearn.impute import SimpleImputer
from sklearn.metrics import confusion_matrix

# Step 1: Load the dataset
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')



# Convert categorical columns to numeric using Label Encoding
categorical_columns = df.select_dtypes(include=['object', 'category']).columns

# Initialize LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to each categorical column (excluding the target 'Churn')
for col in categorical_columns:
    if col != 'Churn':  # Exclude target column
        df[col] = le.fit_transform(df[col])

# Step 3: Exploratory Data Analysis (Optional step for deeper understanding)
# df.describe()  # View basic statistics
# df.info()  # Check for data types and missing values

# Step 4: Split features and target
X = df.drop('Churn', axis=1)  # Features
y = df['Churn']  # Target variable

# Step 5: Split the data into training and testing sets (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 6: Build the Logistic Regression Model
log_reg_model = LogisticRegression(max_iter=1000)

# Train the model
log_reg_model.fit(X_train, y_train)

# Step 7: Make predictions on the test set
y_pred = log_reg_model.predict(X_test)

# Step 8: Assigning scores (probabilities) to predictions
y_prob = log_reg_model.predict_proba(X_test)[:, 1]  # Probabilities for the positive class

# Step 9: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

# Print classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Confusion matrix (for more detailed evaluation)
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Model Accuracy: 80.97%

Classification Report:
               precision    recall  f1-score   support

          No       0.84      0.91      0.87      1539
         Yes       0.69      0.55      0.61       574

    accuracy                           0.81      2113
   macro avg       0.77      0.73      0.74      2113
weighted avg       0.80      0.81      0.80      2113


Confusion Matrix:
 [[1393  146]
 [ 256  318]]

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [37]:
# Import necessary libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Initialize the models (if they were not initialized before)
log_reg = LogisticRegression(max_iter=1000)  # Initialize Logistic Regression
rf = RandomForestClassifier(n_estimators=100, random_state=42)  # Initialize Random Forest
knn = KNeighborsClassifier(n_neighbors=5)  # Initialize K-Nearest Neighbors
sgb = GradientBoostingClassifier(n_estimators=100, random_state=42)  # Initialize Stochastic Gradient Boosting

# Step 2: Fit the models (if they are not already trained)
log_reg.fit(X_train, y_train)
rf.fit(X_train, y_train)
knn.fit(X_train, y_train)
sgb.fit(X_train, y_train)

# Step 3: Create the Voting Classifier ensemble model
voting_clf = VotingClassifier(estimators=[
    ('log_reg', log_reg),
    ('rf', rf),
    ('knn', knn),
    ('sgb', sgb)
], voting='hard')  # 'hard' voting means majority voting for classification

# Step 4: Train the ensemble model
voting_clf.fit(X_train, y_train)  # Fit the ensemble model (if it's not already fitted)

# Step 5: Make predictions on the test set using the ensemble model
y_pred = voting_clf.predict(X_test)

# Step 6: Evaluate the ensemble model
accuracy = accuracy_score(y_test, y_pred)
print(f"Ensemble Model Accuracy: {accuracy * 100:.2f}%")

# Step 7: Print the classification report for detailed performance metrics
print("\nEnsemble Classification Report:\n", classification_report(y_test, y_pred))

# Step 8: Confusion matrix for more insights into classification performance
print("\nEnsemble Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Ensemble Model Accuracy: 79.51%

Ensemble Classification Report:
               precision    recall  f1-score   support

          No       0.81      0.94      0.87      1539
         Yes       0.72      0.40      0.52       574

    accuracy                           0.80      2113
   macro avg       0.76      0.67      0.69      2113
weighted avg       0.78      0.80      0.77      2113


Ensemble Confusion Matrix:
 [[1449   90]
 [ 343  231]]

In [38]:
# Import necessary libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Initialize the models (if they were not initialized before)
log_reg = LogisticRegression(max_iter=1000)  # Initialize Logistic Regression
rf = RandomForestClassifier(n_estimators=100, random_state=42)  # Initialize Random Forest
knn = KNeighborsClassifier(n_neighbors=5)  # Initialize K-Nearest Neighbors
sgb = GradientBoostingClassifier(n_estimators=100, random_state=42)  # Initialize Stochastic Gradient Boosting

# Step 2: Fit the models (if they are not already trained)
log_reg.fit(X_train, y_train)
rf.fit(X_train, y_train)
knn.fit(X_train, y_train)
sgb.fit(X_train, y_train)

# Step 3: Create the Voting Classifier ensemble model
voting_clf = VotingClassifier(estimators=[
    ('log_reg', log_reg),
    ('rf', rf),

    ('sgb', sgb)
], voting='hard')  # 'hard' voting means majority voting for classification

# Step 4: Train the ensemble model
voting_clf.fit(X_train, y_train)  # Fit the ensemble model (if it's not already fitted)

# Step 5: Make predictions on the test set using the ensemble model
y_pred = voting_clf.predict(X_test)

# Step 6: Evaluate the ensemble model
accuracy = accuracy_score(y_test, y_pred)
print(f"Ensemble Model Accuracy: {accuracy * 100:.2f}%")

# Step 7: Print the classification report for detailed performance metrics
print("\nEnsemble Classification Report:\n", classification_report(y_test, y_pred))

# Step 8: Confusion matrix for more insights into classification performance
print("\nEnsemble Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Ensemble Model Accuracy: 80.64%

Ensemble Classification Report:
               precision    recall  f1-score   support

          No       0.84      0.91      0.87      1539
         Yes       0.69      0.52      0.59       574

    accuracy                           0.81      2113
   macro avg       0.76      0.72      0.73      2113
weighted avg       0.80      0.81      0.80      2113


Ensemble Confusion Matrix:
 [[1408  131]
 [ 278  296]]